In [29]:
import numpy as np

In [30]:
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])
A * B

array([[10, 40],
       [30, 80]])

In [31]:
X = np.array([[51, 55], [14, 19], [0, 4]])
print(X)

[[51 55]
 [14 19]
 [ 0  4]]


In [32]:
X[0]

array([51, 55])

In [33]:
X[0][1]

55

In [34]:
## loop
for row in X:
    print(row)

[51 55]
[14 19]
[0 4]


In [35]:
X.shape

(3, 2)

In [36]:
## flatten
X = X.flatten()
print(X)

[51 55 14 19  0  4]


In [37]:
X[np.array([0, 2, 4])]

array([51, 14,  0])

In [38]:
X.dtype

dtype('int64')

In [39]:
X > 15

array([ True,  True, False,  True, False, False])

In [40]:
X[X > 15]

array([51, 55, 19])