In [7]:
import numpy as np

In [8]:
x = np.array([1., 2, 3])
print(x)
type(x)

[1. 2. 3.]


numpy.ndarray

In [9]:
print(type(x))

<class 'numpy.ndarray'>


In [12]:
x = np.array([1., 2, 3])
y = np.array([2., 55, 61])
print(x + y)
print(x - y)
print(x * y)
print(x / y)

[ 3. 57. 64.]
[ -1. -53. -58.]
[  2. 110. 183.]
[0.5        0.03636364 0.04918033]


In [13]:
x = np.array([1, 2, 3])
x / 2.

array([0.5, 1. , 1.5])