In [1]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
A.shape

(2, 2)

In [2]:
B = np.array([[5, 6], [7, 8]])
B.shape

(2, 2)

In [3]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [4]:
C = np.array([[1, 2], [3, 4], [5, 6]])
D = np.array([[1, 2, 3], [4, 5, 6]])

np.dot(C, D)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [5]:
print(np.dot(C, D))

[[ 9 12 15]
 [19 26 33]
 [29 40 51]]
