In [1]:
import numpy as np

a = np.array([0.3, 2.9, 4.0])
exp_a = np.exp(a)

print(exp_a)

[ 1.34985881 18.17414537 54.59815003]


In [2]:
sum_a = np.sum(exp_a)
dis_a = exp_a / sum_a

print(dis_a)

[0.01821127 0.24519181 0.73659691]


In [3]:
print(np.sum(dis_a))

1.0


In [9]:
def softmax(a):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)

    return exp_a / sum_exp_a

def show_softmax(a):
    print(softmax(a))

show_softmax(np.array([0.3, 2.9, 4.0]))

## error
show_softmax(np.array([1010, 1000, 990]))

[0.01821127 0.24519181 0.73659691]
[nan nan nan]


/tmp/ipykernel_237234/1494749149.py:2: RuntimeWarning: overflow encountered in exp
  exp_a = np.exp(a)
/tmp/ipykernel_237234/1494749149.py:5: RuntimeWarning: invalid value encountered in divide
  return exp_a / sum_exp_a


In [12]:
def softmax(a):
    c = np.max(a)
    # overflow handle
    exp_a = np.exp(a - c)

    sum_exp_a = np.sum(exp_a)
    return exp_a / sum_exp_a

y = softmax(np.array([0.3, 2.9, 4.0]))
print(y)
print(np.sum(y))

[0.01821127 0.24519181 0.73659691]
1.0
