In [7]:
# import

import sys, os
sys.path.append(os.pardir)

import numpy as np
from common.functions import softmax, cross_entropy_error
from common.gradient import numerical_gradient

In [8]:
class simpleNet:
    def __init__(self):
        self.W = np.random.randn(2, 3)

    def predict(self, x):
        return np.dot(x, self.W)
    
    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y, t)

        return loss

In [9]:
net = simpleNet()
print(net.W)

[[ 1.18580548 -0.39518233  0.67218078]
 [ 0.2425825   1.32061146  0.91729675]]


In [10]:
x = np.array([0.6, 0.9])
p = net.predict(x)
print(p)

[0.92980754 0.95144091 1.22887555]


In [12]:
np.argmax(p)
t = np.array([0, 0, 1])
net.loss(x, t)

0.9159840648273407